const types = {
  SET_TOKEN: 'SET_TOKEN',
  SEARCH_ALL: 'SEARCH_ALL',
  SET_LISTS: 'SEL_LISTS',
  SET_CURRENT_LIST: 'SET_CURRENT_LIST',
  REMOVE_CURRENT_LIST: 'REMOVE_CURRENT_LIST',
  SET_ALL_ITEMS: 'SET_ALL_ITEMS',
  SET_CURRENT_LIST_ITEMS: 'SET_CURRENT_LIST_ITEMS',
  SET_MODAL_ADD_LIST: 'SET_MODAL_ADD_LIST',
  SET_MODAL_ADD_ITEM: 'SET_MODAL_ADD_ITEM',
};

export default types;
